
from django.db import models
from django.urls import reverse
from django_editorjs_fields import EditorJsJSONField, EditorJsTextField
from django.contrib.auth import get_user_model
from crum import get_current_user
User = get_user_model()

class Post(models.Model):
    #id = models.AutoField(primary_key=True)    #it is automatically generated by django
    title = models.TextField()
    body_editorjs = EditorJsJSONField(readOnly=False, autofocus=True)
    body_custom = EditorJsJSONField(
        plugins=[
            "@editorjs/image",
            "@editorjs/header",
            "@editorjs/list",
            "editorjs-github-gist-plugin",
            "editorjs-hyperlink",
            "@editorjs/code",
            "@editorjs/inline-code",
            "@editorjs/table@1.3.0",
        ],
        tools={
            "Gist": {
                "class": "Gist"
            },
            "Hyperlink": {
                "class": "Hyperlink",
                "config": {
                    "shortcut": 'CMD+L',
                    "target": '_blank',
                    "rel": 'nofollow',
                    "availableTargets": ['_blank', '_self'],
                    "availableRels": ['author', 'noreferrer'],
                    "validate": False,
                }
            },
            "Image": {
                'class': 'ImageTool',
                "config": {
                    "endpoints": {
                        # Your custom backend file uploader endpoint
                        "byFile": "/editorjs/image_upload/"
                    }
                }
            }
        },
        null=True,
        blank=True,
    )

    user = models.ForeignKey(User,on_delete=models.CASCADE,editable=False)
    created_on = models.DateTimeField(auto_now_add=True,null=True)
    updated_on = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('post_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return '{}'.format(self.pk)

    def save(self,*args,**kwargs):   #if we donot do this integrity errors comes
        user = get_current_user()
        if user and not user.pk:
            user = None
        if not self.pk:
            self.user = user
        #print(user)
        super(Post,self).save(*args,**kwargs)


class Comment(models.Model):
    content = EditorJsJSONField(null=True, blank=True)
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE,editable=False)
    created_on = models.DateTimeField(auto_now_add=True,null=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{}'.format(self.pk)

    def save(self,*args,**kwargs):   #if we donot do this integrity errors comes
        user = get_current_user()
        if user and not user.pk:
            user = None
        if not self.pk:
            self.user = user
        #print(user)
        super(Post,self).save(*args,**kwargs)


class Follow(models.Model):
    user = models.ForeignKey(User,related_name='follow_user',on_delete=models.CASCADE,editable=False)
    follower = models.ForeignKey(User,related_name='follow_follower',on_delete=models.CASCADE)
    followed_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user}-->{self.follower}"

    def save(self,*args,**kwargs):   #if we donot do this integrity errors comes
        user = get_current_user()
        if user and not user.pk:
            user = None
        if not self.pk:
            self.user = user
        #print(user)
        super(Post,self).save(*args,**kwargs)

