# Generated by Django 3.2.5 on 2022-11-06 10:11

from django.db import migrations, models
import django.db.models.deletion
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_default', models.TextField()),
                ('body_editorjs', django_editorjs_fields.fields.EditorJsJSONField()),
                ('body_custom', django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True)),
                ('body_textfield', django_editorjs_fields.fields.EditorJsTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='neditor.post')),
            ],
        ),
    ]
